### ISSUE TITLE
can it be installed on beaglebone black and any other screen other than manga?

### ISSUE THREAD

**Issue by amrithmmh** [intelligent-agent/toggle#1]
I am not having a manga 2 screen . Is it possible to install it on beagle bone black and a 7 inch lcd screen touch capacitive?
how can it control the arduino based 3d printer like ramps or any other?(is it via USB connected bectween arduino and beaglebone black?)

**Comment by goeland86** [comment]
Hi @amrithmmh,
Toggle is basically calling on the OctoPrint API. The touchscreen you use is entirely up to you - we designed it based on the Manga-Screen and now for Manga-Screen 2, but if you modify the resolution and themes you can use it on any screen, even with touch disabled. There's a boolean variable whether you want to enable mouse input for Toggle or not.

You can also install Toggle on a Raspberry pi (for example the one where OctoPrint is running). Note that Toggle is not a printer-server by itself, it **requires** OctoPrint with an API key in the local.cfg file to function.

**Comment by amrithmmh** [comment]
@goeland86 thanks for the detailed explanation

**Comment by amrithmmh** [comment]
@goeland86  how to install it on raspberry pi 3 ?
i tried with the official install instruction but they are outdated and not working..

@goeland86  Clutter and cogl are not working in raspberry pi raspbian os.I guess the reason for choosing beaglebone is for the same reason?

**Comment by eliasbakken** [comment]
It's difficult to get Toggle running on a raspberry Pi. I have gotten it working with quite a bit of work, but the instructions are not up to date, so I think we have to leave Rpi as "not supported" for now pending a PR with working instructions.
