### ISSUE TITLE
how to install toggle on raspberry pi 3B+

### ISSUE THREAD

**Issue by amrithmmh** [intelligent-agent/toggle#2]
please add instuction on how to install toggle on raspberry pi and debian instrucions are out of date

**Comment by amrithmmh** [comment]
Is it possible to install it on latest ubuntu ? can anyone give me the instruction to compile it from ubuntu in my desktop computer (not arm), (P.S i do not have any beagle bone black and its costs 5000RS in our country that is half my salary)

**Comment by goeland86** [comment]
@amrithmmh the documentation is (finally) being overhauled - I'll let you know as soon as I've got something useable for you. I know it'll work as I managed to run it on a desktop PC with Ubuntu, but there's an issue nagging me still.

**Comment by amrithmmh** [comment]
@goeland86 thank you..i will keep an eye on the documentation

**Comment by eliasbakken** [comment]
Some work was done to try and port Toggle to Raspberry Pi a while ago, but the work was never completed. Unless there is an interested in trying to revive that work, I think we should put a pin in it for now.
