### ISSUE TITLE
configuration help for 7" 800x480 touchscreen

### ISSUE THREAD

**Issue by gaby64** [intelligent-agent/toggle#28]
the toggle interface is appearing cut down to 1/4

I have tried setting the screen resolution in local.cfg to no effect.

https://drive.google.com/open?id=1wcG6v_J9wFV5hnhx0ssRJJXFu1mCq958
https://drive.google.com/open?id=1n2db7pAWl19V62klsU5pKPzFv4qUsk-o

**Comment by goeland86** [comment]
@gaby64 it looks like it's using a fullHD resolution theme instead of the 800x480 one...

**Comment by gaby64** [comment]
CRITICAL   File "/usr/local/Toggle-1_3_x/bin/toggle", line 11, in <module>
CRITICAL load_entry_point('Toggle', 'console_scripts', 'toggle')()
CRITICAL   File "/usr/local/Toggle-1_3_x/src/toggle/toggle/Toggle.py", line 274, in main
CRITICAL
CRITICAL t = Toggle()
CRITICAL   File "/usr/local/Toggle-1_3_x/src/toggle/toggle/Toggle.py", line 132, in __init__
CRITICAL
CRITICAL config.temp_graph = TemperatureGraph(config)
CRITICAL   File "/usr/local/Toggle-1_3_x/src/toggle/toggle/TemperatureGraph.py", line 81, in __init__
CRITICAL
CRITICAL btn.add_action(tap)
CRITICAL AttributeError
CRITICAL :
CRITICAL 'NoneType' object has no attribute 'add_action'

**Comment by goeland86** [comment]
Hmm, looks like we need to update the 800x480 theme file to match the newer definitions.

**Comment by Wackerbarth** [comment]
Since @gaby64 got it working, perhaps he will provide us a pull request to do so.

**Comment by eliasbakken** [comment]
ui_800x480 has been updated with PR#56
