### ISSUE TITLE
Running toggle on beaglebone black (not wireless) halts on network.py, assigning a wireless ap

### ISSUE THREAD

**Issue by electronlove** [intelligent-agent/toggle#3]
Switched to develop branch of toggle and installed dependency python-networkmanager.  Toggle exits with an attribute error "CRITICAL 'NoneType' object has no attribute 'ActiveAccessPoint" at line 175 in /usr/local/lib/python2.7/dist-packages/toggle/Network.py", in get_access_points.  This error results from attempting to run toggle on a beagle bone black without WiFi (which does not require an access point).

**Comment by ThatWileyGuy** [comment]
This is fixed in ecee99e9e5507862c32947df261bfc11e4c3f5e0.
