### ISSUE TITLE
Model Selection from Screen

### ISSUE THREAD

**Issue by BrunoSonego** [intelligent-agent/toggle#45]
Selecting models directly from screen to print (by the side arrows) is not working. it keeps loading the model forever. but selecting from octoprint it loads and shows ok

**Comment by goeland86** [comment]
@BrunoSonego do you have STL files loaded or only gcode files?
As far as I know if the STL & Gcode have matching file names, the selector should load the STL and display properly. Loading gcode is currently broken.

**Comment by BrunoSonego** [comment]
i have STL and Gcode with same name in the models folder. it works ok when selecting from octoprint. just dont load when selecting from screen

**Comment by eliasbakken** [comment]
In v1.4.0 you can now choose gcode files, but both local and sd-card files are reported by octoprint and toggle does not make a distinction yet, so it tries to load both files. This causes the spinner to appear and not go away on every other model.

**Comment by goeland86** [comment]
@eliasbakken maybe we should put in a filter to exclude file names beginning with `/` in general? Normally those are the ones that come "from SD"

**Comment by BrunoSonego** [comment]
or some way to navigate in folder and select files. that way i could use a pendrive in the usb and select to print without turning on my computer

**Comment by eliasbakken** [comment]
In the latest master, it is possible to select models in the root folder using the arrow keys.
