### ISSUE TITLE
Suddenly toggle stopped working...

### ISSUE THREAD

**Issue by javimurcia** [intelligent-agent/toggle#60]
I don't know if this is the correct place to post this, but today, out of the blue after a reboot, toggle no longer works. Here is the error it shows:
04-12 09:53 root         INFO     Initializing  Toggle 1.4.0.post.dev7
04-12 09:53 root         INFO     Using config file /etc/toggle/default.cfg
04-12 09:53 root         INFO     Using config file /etc/toggle/thing-delta-1080p.cfg
04-12 09:53 root         INFO     Using config file /etc/toggle/local.cfg
PVR:(Error): PVRSRVBridgeCall: Failed to access device.  Function ID:3223086849 (strerror returns no value.). [0, ]
PVR:(Error): PVRSRVEnumerateDevices: BridgeCall failed [0, ]
PVR:(Error): PVRSRVConnect: Unable to enumerate devices. [0, ]
PVR:(Error): Couldn't connect to services [0, ]
04-12 09:53 root         CRITICAL /usr/local/Toggle-dev/src/toggle/toggle/Toggle.py:99: Warning: g_strsplit: assertion 'string != NULL' failed
  Clutter.init(None)

Segmentation fault

Also, in dmesg the following shows up, which might be relevant:
[  884.772034] PVR_K:(Error): BridgedDispatchKM: Driver initialisation not completed yet.

Full dmesg output: https://pastebin.com/HwsbUFrt

¿any idea of what i've messed up? because i'm clueless...

**Comment by goeland86** [comment]
@javimurcia can you tell us what image you're running on? Have you run apt-get update/upgrade recently?

**Comment by javimurcia** [comment]
sorry i had forgotten: Umikaze-2.2.1-RC3

No apt-get upgrades just before this problem (although the image has been updated at some point).

the problem is that the printers has been running non-stop for five days, and i can't recall if during those 5 days i've done something that can cause this problem (altought i'm 99% sure about the no apt-get upgrade part)

**Comment by goeland86** [comment]
Hrm. It could be some kind of issue with the graphics driver then.

Can you try to reboot the BBB soon-ish, to check if it comes back on?

**Comment by javimurcia** [comment]
Already did that several times, same result.

I think the dmesg message "Driver initialisation not completed yet" only appears when i try to start toggle, if toggle isn't started the message doesn't show (ill confirm when i'm able to reboot the printer)

**Comment by goeland86** [comment]
Hrm. This is peculiar, and the driver initialisation issue points to a system fault rather than a Toggle problem itself.

**Comment by eliasbakken** [comment]
I'm closing this, it's too old to be relevant.
